# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc8278d74ad0554dcd5a0f61fd7698e7444c6937cde3881b4f867c7cf65b14010fcbe656143d5b3e70ce3dfcd5c869b3b2ee11a7d1ac26d7f918a1e614c73b01

test:
  secret_key_base: e7dbc28f335115628da1d2913aced0bfdb8a8eb9501c02828cc86dd381e2504b4995d6bfad58b5af1984dba73efb5786f8f629ae3117375394e9a6837383042a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
